const skills=[['SQL','9.5/10',95],['Python','9/10',90],['dbt','9/10',90],['Looker','9/10',90],['Tableau','9/10',90],['Metabase','9/10',90],['AWS Redshift','9/10',90],['Google BigQuery','9/10',90],['Fivetran','9/10',90],['Apache Airflow','8/10',80],['PySpark','8/10',80],['Docker','8/10',80],['Apache Iceberg','8/10',80],['Google Cloud IAM','8/10',80],['AWS S3','8/10',80],['Cube.dev','8/10',80],['Kubernetes','7/10',70],['Google Cloud Pub/Sub','7/10',70],['Claude API','7/10',70]];
const experience=[
['JS','Juniper Square','Senior Analytics Engineer','Feb 2026 — Present',['LookML','dbt','Looker','Amazon Redshift','AWS S3','Apache Airflow'],['Partnering with Product, Data Platform, and Client Success on engagement, activation, and retention metrics.','Designing LookML semantic models, dbt transformations, Explores, and dashboards for product and leadership stakeholders.','Owning event tracking plans and metric governance for key platform workflows.','Building dimensional models and SQL-driven analytics across user and account data.']],
['VV','VeVe','Senior Analytics Engineer','Aug 2025 — Feb 2026',['dbt','Looker','LookML','Apache Iceberg','Redshift','AWS S3'],['Owned product analytics for a B2C mobile app across activation, engagement, retention, and monetization.','Modeled funnels and cohorts from install through paid conversion and churn.','Established event tracking standards and data-quality practices with Engineering.','Analyzed onboarding, activation, and monetization A/B tests to inform product and growth decisions.']],
['JA','Jiva Ag','Senior Data Analyst','Aug 2022 — Aug 2025',['dbt','Apache Airflow','Amazon Redshift','Fivetran','Mixpanel','CleverTap'],['Built the analytics system and metric frameworks from scratch across sales, product, marketing, and engineering.','Established event tracking plans across engagement, churn, and drop-off analysis.','Developed a Python SARIMAX model and deployed a Flask app for Feedmill price forecasting.','Built Metabase and Looker dashboards for Business, Operations, Product, and Design teams.','Designed dimensional models and a semantic layer for governed reporting.']],
['MG','MoneyGram','Business Intelligence Analyst','Feb 2021 — Jul 2022',['BigQuery','GCP','LookML','Fivetran','Looker'],['Developed KPIs, dashboards, and insights from a GCP-hosted data warehouse.','Optimized SQL for customer segmentation, campaign performance, loyalty, and subscription analysis.','Built cohort, retention, churn, and lifetime-value analyses to guide marketing strategy.','Designed GCP data models and automated dashboards, and trained end users on Looker.']],
['HF','Harvest','Data Analyst','Sep 2020 — Dec 2020',['SQL','SSRS','Power BI','Excel'],['Cleaned and transformed data feeds from multiple applications.','Developed reporting workflows with SQL stored procedures, functions, and SSRS.','Produced asset valuation and customer-growth reporting in Power BI.','Built master distribution reports for funds liquidity and distributions.']],
['TCS','Tata Consultancy Services','Systems Engineer / Data Analyst','Jun 2016 — Jul 2019',['SQL','Python','Tableau','SSIS','SSRS'],['Led analytics lifecycle work across data modeling, acquisition, reporting, and product support.','Built Tableau KPI dashboards for global SLA and OLA compliance.','Performed ad hoc analysis with Python to support data-driven decisions.','Created executive consumer-banking reporting and SQL-based RDBMS environments.','Maintained database objects, reporting procedures, and pipeline automation.']]
];
const projects=[
['Multi-Document-RAG',['Python','Vector Database','LLM','RAG'],'A retrieval-augmented workflow for answering questions across complex document collections.'],
['Rental Analytics',['SQL','BigQuery','Looker'],'A decision layer for rental performance, market signals, and operational opportunity.'],
['Dash Forecasting',['Python','SARIMAX','Time Series'],'Feedmill business forecasting powered by a SARIMAX time-series model.'],
['dbt Project',['dbt','Apache Iceberg','Looker','BigQuery','SQL'],'Semantic-layer patterns, event models, and reusable dbt transformations for governed analytics.'],
['Mall Customer Segmentation',['Python','KMeans','BigQuery','GCP'],'Customer segmentation based on behavioural, demographic, and purchasing patterns.'],
['Europe Hotel Reviews Sentiment Analysis',['Python','NLP','Sentiment Analysis'],'TripAdvisor review analysis paired with a content-based recommendation approach.'],
['Rotten Tomatoes Movie Review Analysis',['Python','Machine Learning','NLP'],'Exploring movie-review patterns and natural-language sentiment signals.']
];
document.querySelector('#skills-grid').innerHTML=skills.map(([name,level,score])=>`<article class="skill"><div><b>${name}</b><div class="meter"><i style="width:${score}%"></i></div></div><small>${level}</small></article>`).join('');
document.querySelector('#experience-timeline').innerHTML=experience.map(([logo,company,title,duration,tech,achievements])=>`<li class="career-item reveal"><i class="career-dot"></i><article class="career-card"><div class="career-top"><span class="company-logo" aria-label="${company} logo placeholder">${logo}</span><div><h3>${company} <em>/ ${title}</em></h3></div><span class="career-duration">${duration}</span></div><div class="career-tech">${tech.map(item=>`<span>${item}</span>`).join('')}</div><ul class="career-achievements">${achievements.map(item=>`<li>${item}</li>`).join('')}</ul></article></li>`).join('');
document.querySelector('#project-grid').innerHTML=projects.map(([name,tech,outcome],i)=>`<article class="project reveal"><span class="project-num">PROJECT / ${String(i+1).padStart(2,'0')}</span><div><h3>${name}</h3><p class="project-outcome">${outcome}</p><div class="project-tech">${tech.map(item=>`<span>${item}</span>`).join('')}</div></div></article>`).join('');
document.querySelector('#year').textContent=new Date().getFullYear();
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const toggle=document.querySelector('.theme-toggle');const stored=localStorage.getItem('theme');if(stored==='light')document.body.classList.add('light');toggle.addEventListener('click',()=>{document.body.classList.toggle('light');localStorage.setItem('theme',document.body.classList.contains('light')?'light':'dark')});
const glow=document.querySelector('.cursor-glow');window.addEventListener('pointermove',e=>{glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'},{passive:true});
